### ISSUE TITLE
groovy syntax not recognized in the windowing cli

### ISSUE THREAD

**Issue by achaubal** [hbutani/SQLWindowing#2] opened 2012-01-30 18:05 UTC
hi,

I am able to make a connection from the client to the metastore service and run a hive query
 hive --service windowingCli -w /tmp/windowing/com.sap.hadoop.windowing-0.0.1-SNAPSHOT-jar-with-dependencies.jar

however, when I type a query, it does not recognize the syntax,

hive> from <select a1,a2,a8 from matest >
    > partition by a1
    > order by a1, a2 asc
    > with rank() as r,
    > select a1,a2,a8,r;
FAILED: Parse Error: line 1:5 cannot recognize input near '<' 'select' 'a1' in join source.

What am I missing?

thanks for your help

ameet

**Comment by hbutani** [comment] 2012-01-30 18:09
Switch to windowing mode

Issue wmode windowing;

To check what mode you are in just issue wmode;

**Comment by achaubal** [comment] 2012-01-30 18:51
thanks harish for the quick response, that did it and I was able to successfully run the first query with a function first_value

a few observations,
1. Groovy syntax doesn't like space inside <>
   hive> from <select a1,a2,a8 from matest >
   
   > partition by a1
   > order by a1, a2 asc
   > with rank() as r,
   > select a1,a2,a8,r;
   > Failed windowing query from <select a1,a2,a8 from matest >
   > partition by a1
   > order by a1, a2 asc
   > with rank() as r,
   > select a1,a2,a8,r Parse Error:MismatchedTokenException(48!=19)
2. Sometimes it doesn't execute the query till I type "quit"

hive> from  <matest>
    > partition by a1 order by a1, a2
    > with first_value(a2) as first_date, first_value(a8) as first_a8
    > select a1,a2,first_date,first_a8 into path='/user/ameet/matest_wnd_justtname';
hive>
    > ;
hive>
    > ;
hive> quit;
FAILED: Parse Error: line 1:49 cannot recognize input near 'matest' '<EOF>' '<EOF>' in select clause
1.  It doesn't like the table name inside <> as the source
   hive> from  <matest>
   
   > partition by a1 order by a1, a2
   > with
   > first_value(a2) as first_date, first_value(a8) as first_a8
   > select a1,a2,first_date,first_a8 ;
   > FAILED: Parse Error: line 1:49 cannot recognize input near 'matest' '<EOF>' '<EOF>' in select clause
2.   It wants to write and move things from /user/hive/warehouse, which was a write protected directory for an ordinary user in my case. I had to make it 777 to allow windowing to write to. It finally worked that way for me.
   hive> from <select * from matest>
   
   > partition by a1 order by a1, a2
   > with
   > first_value(a2) as first_date, first_value(a8) as first_a8
   > select a1,a2,first_date,first_a8 into path='/user/ameet/matest_wnd';

The results were sorted and kept in the destination dir with the correct values for first_value function. ( :) thx )
1.    I have not been able to make it work without the "into path='a path' " syntax yet.

**Comment by hbutani** [comment] 2012-01-30 19:24
Thanks Ameet, this valuable feedback. Let me try to address each of the questions:
1. Groovy syntax doesn't like space inside <>
   This sounds like a bug. Will test, fix and add a unit test...
2. It doesn't like the table name inside <> as the source
   Yes the grammar treats the 2 use cases differently: for a hive tablename you shouldn't enclose in <>; whereas a hive query needs to be. This is a good point; I will add it to my list of enhancements. I presume this is a minor inconvenience so this may not get resolved soon.
3. I have not been able to make it work without the "into path='a path' " syntax yet.
   Currently you have to specify an output path. Plan to support CTAS style statements and hive cli style queries where the results are shown in the client; but are not yet implemented.
4. It wants to write and move things from /user/hive/warehouse, which was a write protected directory for an ordinary user in my case. I had to make it 777 to allow windowing to write to.

Not sure what happened here. Were you specifying the into path clause? One thing to note is that under the covers (when you specify a hive query as the input) it issues a CTAS statement in hive ( you will see new tables with the prefix windowing in ur db).

**Comment by achaubal** [comment] 2012-01-30 19:32
hi Harish,

about that final point about the path.
Yes, I do see the tables in hive prefixed with windowingtemptable like : windowingtemptable_1327947784933
however, the problem is that this table is stored in an HDFS path at /user/hive/warehouse which is the default path for any hive table. Now although I specified an "into path = 'my/path' " syntax, it still created the dir under /user/hive/warehouse for this CTAS table windowingtemptable_1327947784933. Additionally, it created a directory with 'my/path' as well, which is fine.
The problem is that the path /user/hive/warehouse is kinda sacrosanct in my mind, there could be other important tables and I wouldn't want an ordinary user to have the ability to go there and create delete directories.
So, is there a way to specify that the temporary tables are NOT created in that directory ?

thanks

ameet

**Comment by hbutani** [comment] 2012-01-30 19:57
Ok I understand now.
1. The windowingtemptable is for the output of the driving Hive Query. Just checked the Hive manual, a CTAS table cannot be an external table. So the issue you raise is not unique to SQLWindowing.  This is something they spell out in their Authorization & Authentication guides: Hive only controls whether you are allowed to execute a query; for data you must ensure you have the right (read/write) priviliges in HDFS.
2. The path you specify in the query is for the final output of the SQLWindowing query.

Look at the from <hive query>... as a convenience for the 2 manual steps:
- issue a MR job/Hive Query and create a hive table
- issue a SQL Windowing query on the above hive table. The result of this is saved in the path specified.

Does this make sense? I get what you were expecting, but I don't see how to make it easier for a user. 
Do you have any suggestions. (BTW one more thing on the todo list is the cleanup of these temptables.)

**Comment by hbutani** [comment] 2012-01-30 19:58
Look at the from ... as a convenience for the 2 manual steps:

should be:
Look at the 'from <hive query>...' as a convenience for the 2 manual steps:

**Comment by achaubal** [comment] 2012-01-30 20:42
yes, makes sense . forgot about the CTAS bit.. 
I guess, since you are doing CTAS, there is not alternative.
Would it be possible to NOT create the table? i.e. instead of CTAS, just run 
insert overwrite directory 'my/foo/dir' select \* from mytable;

while making sure that the correct field delimiters are chosen? i.e. comma?

so that I can store the output of this into a directory and then build an external table if needed.

because, if you think about it, the user when running this windowing query is not thinking in terms of creating a table.
If he/she wants to do that, she can always do an explicit CTAS like
create myWindowingTable 
as 
( my windowing query using your window jar );
--assuming that is possible.

thanks

ameet

**Comment by hbutani** [comment] 2012-01-30 22:07
Yes this is coming. Was planning a table = '..' part to the output clause. This would create a external table in hive.

**Comment by achaubal** [comment] 2012-01-31 00:37
When I was trying to run the following query,

from <select * from matest>
    partition by a1 order by a1, a8
     with rank()  as myrank, sum ( a8) over rows between 3 preceding and current row as a8_last3
    select a1, a2, myrank, a8_last3 
into path='matest_wind_2';

I get a weird behavior.
The query runs and says moving data, 50 rows, and comes back to prompt with time indicating that it completed successfully,
2012-01-30 19:32:53,040 Stage-1 map = 0%,  reduce = 0%
2012-01-30 19:32:56,068 Stage-1 map = 100%,  reduce = 0%
2012-01-30 19:32:58,092 Stage-1 map = 100%,  reduce = 100%
Ended Job = job_201201151510_0117
Ended Job = -36019062, ...
..

However an ls in other window shows nothing in that target dir, just a _temporary and _logs dir and nothing else.

when I type quit in the hive window, I get a spew,
attempt_201201151510_0118_r_000000_1:           sum(alias=a8_last3, param=[id=a8], type=null, window=window(start=range(3 PRECEDING), end=currentRow))]
attempt_201201151510_0118_r_000000_1:   select=a1, a2, myrank, a8_last3
attempt_201201151510_0118_r_000000_1:   whereExpr=null
attempt_201201151510_0118_r_000000_1:   tableOutput=(output(path=matest_wind_2, serde=org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe, serDeProps={field.delim=,, columns=a1,a2,myrank,a8_last3, columns.types=int,string,int,float}, format=org.apache.hadoop.mapred.TextOutputFormat)
attempt_201201151510_0118_r_000000_2: Query:
attempt_201201151510_0118_r_000000_2:   tableInput=(hiveTable=WindowingTempTable_1327969969642)
attempt_201201151510_0118_r_000000_2:   partitionColumns=a1
attempt_201201151510_0118_r_000000_2:   orderColumns=a1 ASC, a8 ASC
attempt_201201151510_0118_r_000000_2:   funcSpecs=[rank(alias=myrank, param=[], type=null, window=null),
attempt_201201151510_0118_r_000000_2:           sum(alias=a8_last3, param=[id=a8], type=null, window=window(start=range(3 PRECEDING), end=currentRow))]
attempt_201201151510_0118_r_000000_2:   select=a1, a2, myrank, a8_last3
attempt_201201151510_0118_r_000000_2:   whereExpr=null
attempt_201201151510_0118_r_000000_2:   tableOutput=(output(path=matest_wind_2, serde=org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe, serDeProps={field.delim=,, columns=a1,a2,myrank,a8_last3, columns.types=int,string,int,float}, format=org.apache.hadoop.mapred.TextOutputFormat)
Failed windowing query quit java.io.IOException: Job failed!

What's happening here?

ameet

**Comment by hbutani** [comment] 2012-01-31 00:58
The initial hive CTAS query ran fine. But the SQLWindowing MR job has failed. (internally the SQLWindowing client is run in a separate java process which submits a job to the MR cluster; the reason for this is antlr jar mismatch between hive and SQLWindowing. Looks like the output from the SQLWindowing client process was not flushed to the hive cli parent process in a timely fashion. Very likely this piece of the system needs some improvements).

But the root cause is something in the SQLWindowing process or the MR job being invoked.

Send me the entire error message that you see. IOException seems to imply something to do with the output path specified. It is not clear to me whether the MR job even got submitted in this case. Can you verify this; if one got invoked: can you send me the stacktrace from the MR task attempt; this should be in the log file for the MR task. The name of the job looks like this: 'Windowing Query: Query:tableInput=.....'

[If this is confusing, looking at Figure 2 in the document might help...]

**Comment by achaubal** [comment] 2012-01-31 01:06
actually the error is :
ERROR="java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Float"
the column I am trying to add is a8 which is float and I am doing a 

sum ( a8)     over rows between 3 preceding and current row as a8_last3,

I even tried sum ( a8)     over rows between 3 preceding and current row as a8_last3[float] but to no avail.

How can I get around this?

thanks
ameet

**Comment by hbutani** [comment] 2012-01-31 01:27
You are really giving this a detailed test drive( thank you :) )

Groovy likes everything to be doubles. Can you try these 2 things:
1. specify type as double
   from<select * from matest>
    partition by a1 order by a1, a8
     with rank()  as myrank, sum ( a8) over rows between 3 preceding and current row as a8_last3[double]
    select a1, a2, myrank, a8_last3
   into path='matest_wind_2';
2. cast input column as double:
   from<select a1, cast(a8 as double) from matest>
    partition by a1 order by a1, a8
     with rank()  as myrank, sum ( a8) over rows between 3 preceding and current row as a8_last3
    select a1, a2, myrank, a8_last3
   into path='matest_wind_2';

This is definitely a major bug. Have somethings to finish right now; but will look at it asap for a solution w/o a workaround.

On a related note, when and if you are ready and willing: could you send me separate note on what the context of your use case is: what functionality, query ifc you would like etc. It will help me prioritise my work; for e.g. I have started to work on Time Series Use cases(look at the FlightsDB test cases checked in), and am looking at supporting Aster MR style pure table functions(for eg for Market Basket Analysis). But if you have specific use cases then I can prioritise them higher on the list.

**Comment by hbutani** [comment] 2012-01-31 04:02
Not able to reproduce couple of these issues. 
1. See com.sap.hadoop.windowing.functions.FloatTest. float or double works. I misspoke earlier; in groovy a constant is by default a double; but in your case you are only using the column. Send me your table defn and a couple of rows of sample data; will try to reproduce the issue...
2. Regarding your spaces in embedded Hive Query; cannot reproduce this either. See com.sap.hadoop.windowing.runtime.mr.EmbeddedHiveQueryTest:testSpacesInHiveQuery

**Comment by achaubal** [comment] 2012-01-31 12:53
ok casting as double did work:

from <select a1,a2,cast(a8 as double) as na8 from matest>
    partition by a1 order by a1, a2
     with rank()  as myrank, 
 sum ( na8)  over rows between 3 preceding and current row as a8_last3 
    select a1, a2, myrank, a8_last3 
into path='matest_wind_1';

couple of observations,
1. when the query finishes in hive and shows that the query was successful and data moved, for quite some time, the target dir does not appear in hadoop dfs -ls. There is a considerable lag when I try to ls in a diff window. Not sure why that's happening.
2. the temporary table created by that job shows different data from the final file generated. The file generated did have the correct data but the temp table threw me off a bit.

**Comment by achaubal** [comment] 2012-01-31 14:36
ok , I know what's happening to the delay,

there are 2 jobs that get launched sometimes, depending on the query
hive> from <select   bc_prod_acct_no , bc_sys_sor_dt ,cv_ratio
    >        from    window_2011_05>
    >   partition    by bc_prod_acct_no
    >       order    by bc_prod_acct_no,bc_sys_sor_dt
    > with rank()  as myrank,
    >      avg (cv_ratio) over
    >        rows between 4 preceding and current row as ma_4_ratio
    > select bc_prod_acct_no , bc_sys_sor_dt,ma_4_ratio
    > into path='ma_4_prod_acct';
Total MapReduce jobs = 2
Launching Job 1 out of 2

But the hive screen just shows one job and tells that everything succeeded and x rows were moved, however going to the jobtracker UI, one can see that the other job is still running and that's why the hadoop dfs -ls doesn't show the target dir created.

does it make sense?

**Comment by achaubal** [comment] 2012-01-31 16:18
ran a simple moving average over last 5 values:
from <select   acct_no , to_date(some_dt) some_date,
               myscore
       from    window_2011_05>
  partition    by acct_no 
      order    by acct_no,some_date asc
with avg (myscore) over 
       rows between 4 preceding and current row as ma_4_ratio 
select acct_no , some_date,ma_4_ratio 
into path='ma_4_prod_acct';

ran successfully, rows = 5.5 mill, time = step1> CTAS of temp table = 30 sec, step2> windowing = 2min, 31 sec.
total time = 3 min, ec2 hadoop cluster = 20 nodes. probably not optimized yet in terms of reduce processes and such , but a basic benchmark.

thanks

ameet

**Comment by hbutani** [comment] 2012-01-31 16:29
Yes exactly. The first Job is executing a Hive Query. The 2nd Job is generated from the SQLWindowing layer; hive is not aware of this.
AS I said the bridging between the Hive CLI and the SQLWindowing Engine could use some engineering bandwidth... One of the things is better reporting on the progress of the SQLWindowing job.

**Comment by hbutani** [comment] 2012-01-31 16:33
Thanks for some hard numbers.
Try this:
set mapred.reduce.tasks=10;

So any settings you enter in the hive cli will get applied to the SQLWindowing engine.

**Closed as completed** 2012-01-31 19:18 UTC
